version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=birdr
      - POSTGRES_PASSWORD=birdr
      - POSTGRES_DB=birdr_development
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data